/**
 * Created by Denis on 15.05.2017.
 */
var krosmasters = {
    "Queen of the Tofus": {
        "name": "Queen of the Tofus",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/arena/1",
        "level": "3",
        "initiative": "8",
        "mp": "4",
        "hp": "8",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/014_i18n_front.png"
    },
    "King of the Gobballs": {
        "name": "King of the Gobballs",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/arena/2",
        "level": "3",
        "initiative": "2",
        "mp": "3",
        "hp": "10",
        "ap": "7",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/015_i18n_front.png"
    },
    "Boo Ming": {
        "name": "Boo Ming",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks1/1",
        "level": "2",
        "initiative": "2",
        "mp": "3",
        "hp": "7",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/025_i18n_front.png"
    },
    "Bad Aboum": {
        "name": "Bad Aboum",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks1/2",
        "level": "3",
        "initiative": "3",
        "mp": "3",
        "hp": "9",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/010_i18n_front.png"
    },
    "Remington Smisse": {
        "name": "Remington Smisse",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks1/3",
        "level": "5",
        "initiative": "5",
        "mp": "4",
        "hp": "13",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/024_i18n_front.png"
    },
    "Maskun John": {
        "name": "Maskun John",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks1/4",
        "level": "2",
        "initiative": "4",
        "mp": "3",
        "hp": "7",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/033_i18n_front.png"
    },
    "Kassius Kaos": {
        "name": "Kassius Kaos",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks1/5",
        "level": "3",
        "initiative": "4",
        "mp": "3",
        "hp": "9",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/013_i18n_front.png"
    },
    "Victor don Voom": {
        "name": "Victor don Voom",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks1/6",
        "level": "5",
        "initiative": "9",
        "mp": "4",
        "hp": "14",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/034_i18n_front.png"
    },
    "Bill Tell": {
        "name": "Bill Tell",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks1/7",
        "level": "3",
        "initiative": "7",
        "mp": "3",
        "hp": "6",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/008_i18n_front.png"
    },
    "Jems Blond": {
        "name": "Jems Blond",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks1/8",
        "level": "4",
        "initiative": "8",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/016_i18n_front.png"
    },
    "Luk Ylook": {
        "name": "Luk Ylook",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks1/9",
        "level": "2",
        "initiative": "6",
        "mp": "3",
        "hp": "5",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/017_i18n_front.png"
    },
    "Lil Healey": {
        "name": "Lil Healey",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks1/10",
        "level": "3",
        "initiative": "1",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/009_i18n_front.png"
    },
    "Ally McZeal": {
        "name": "Ally McZeal",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks1/11",
        "level": "4",
        "initiative": "3",
        "mp": "3",
        "hp": "11",
        "ap": "7",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/021_i18n_front.png"
    },
    "Di Curey": {
        "name": "Di Curey",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks1/12",
        "level": "1",
        "initiative": "0",
        "mp": "3",
        "hp": "5",
        "ap": "5",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/022_i18n_front.png"
    },
    "Srammy": {
        "name": "Srammy",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks1/13",
        "level": "2",
        "initiative": "8",
        "mp": "3",
        "hp": "6",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/031_i18n_front.png"
    },
    "Oscar Kass": {
        "name": "Oscar Kass",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks1/14",
        "level": "3",
        "initiative": "6",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/012_i18n_front.png"
    },
    "Fraktor": {
        "name": "Fraktor",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks1/15",
        "level": "4",
        "initiative": "4",
        "mp": "3",
        "hp": "12",
        "ap": "7",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/032_i18n_front.png"
    },
    "Coa Gulary": {
        "name": "Coa Gulary",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks1/16",
        "level": "1",
        "initiative": "6",
        "mp": "3",
        "hp": "7",
        "ap": "5",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/026_i18n_front.png"
    },
    "Anna Tommy": {
        "name": "Anna Tommy",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks1/17",
        "level": "3",
        "initiative": "9",
        "mp": "3",
        "hp": "12",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/011_i18n_front.png"
    },
    "Clot the Crapulous": {
        "name": "Clot the Crapulous",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks1/18",
        "level": "4",
        "initiative": "4",
        "mp": "3",
        "hp": "14",
        "ap": "7",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/027_i18n_front.png"
    },
    "Klor Ofil": {
        "name": "Klor Ofil",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks1/19",
        "level": "4",
        "initiative": "4",
        "mp": "4",
        "hp": "7",
        "ap": "5",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/028_i18n_front.png"
    },
    "Makum Bah": {
        "name": "Makum Bah",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks1/20",
        "level": "4",
        "initiative": "6",
        "mp": "3",
        "hp": "13",
        "ap": "7",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/030_i18n_front.png"
    },
    "Fern Sockem": {
        "name": "Fern Sockem",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks1/21",
        "level": "1",
        "initiative": "2",
        "mp": "3",
        "hp": "6",
        "ap": "5",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/029_i18n_front.png"
    },
    "Quentin Flush": {
        "name": "Quentin Flush",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks1/22",
        "level": "1",
        "initiative": "2",
        "mp": "3",
        "hp": "6",
        "ap": "5",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/020_i18n_front.png"
    },
    "Dani OShun": {
        "name": "Dani OShun",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks1/23",
        "level": "4",
        "initiative": "5",
        "mp": "4",
        "hp": "12",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/018_i18n_front.png"
    },
    "Naz Rael": {
        "name": "Naz Rael",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks1/24",
        "level": "2",
        "initiative": "3",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/019_i18n_front.png"
    },
    "Percimol": {
        "name": "Percimol",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks1/25",
        "level": "5",
        "initiative": "2",
        "mp": "3",
        "hp": "17",
        "ap": "7",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/035_i18n_front.png"
    },
    "Shak Shaka": {
        "name": "Shak Shaka",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks1/26",
        "level": "5",
        "initiative": "0",
        "mp": "3",
        "hp": "15",
        "ap": "7",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/036_i18n_front.png"
    },
    "Goultard": {
        "name": "Goultard",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks1/27",
        "level": "6",
        "initiative": "7",
        "mp": "4",
        "hp": "16",
        "ap": "8",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/023_i18n_front.png"
    },
    "Cloud Knight": {
        "name": "Cloud Knight",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks1/28",
        "level": "3",
        "initiative": "6",
        "mp": "4",
        "hp": "8",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/038_i18n_front.png"
    },
    "Drop Knight": {
        "name": "Drop Knight",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks1/29",
        "level": "3",
        "initiative": "2",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/039_i18n_front.png"
    },
    "Flame Knight": {
        "name": "Flame Knight",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks1/30",
        "level": "3",
        "initiative": "4",
        "mp": "3",
        "hp": "9",
        "ap": "7",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/040_i18n_front.png"
    },
    "Leaf Knight": {
        "name": "Leaf Knight",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks1/31",
        "level": "3",
        "initiative": "0",
        "mp": "3",
        "hp": "11",
        "ap": "5",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/041_i18n_front.png"
    },
    "Darkness Knight": {
        "name": "Darkness Knight",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks1/32",
        "level": "6",
        "initiative": "8",
        "mp": "4",
        "hp": "15",
        "ap": "7",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/037_i18n_front.png"
    },
    "Argon Gass": {
        "name": "Argon Gass",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf/1",
        "level": "3",
        "initiative": "3",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/001_i18n_front.png"
    },
    "Amalia": {
        "name": "Amalia",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf/2",
        "level": "3",
        "initiative": "4",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/002_i18n_front.png"
    },
    "Evangelyne": {
        "name": "Evangelyne",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf/3",
        "level": "3",
        "initiative": "8",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/003_i18n_front.png"
    },
    "Nox": {
        "name": "Nox",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf/4",
        "level": "6",
        "initiative": "10",
        "mp": "2",
        "hp": "14",
        "ap": "8",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/004_i18n_front.png"
    },
    "Ruel Stroud": {
        "name": "Ruel Stroud",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf/5",
        "level": "3",
        "initiative": "6",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/005_i18n_front.png"
    },
    "Percedal": {
        "name": "Percedal",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf/6",
        "level": "3",
        "initiative": "2",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/006_i18n_front.png"
    },
    "Yugo": {
        "name": "Yugo",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf/7",
        "level": "3",
        "initiative": "7",
        "mp": "3",
        "hp": "8",
        "ap": "7",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/007_i18n_front.png"
    },
    "Goultard the Barbarian": {
        "name": "Goultard the Barbarian",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf/8",
        "level": "6",
        "initiative": "5",
        "mp": "3",
        "hp": "25",
        "ap": "8",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/042_i18n_front.png"
    },
    "Count Frigost": {
        "name": "Count Frigost",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf/9",
        "level": "6",
        "initiative": "6",
        "mp": "5",
        "hp": "14",
        "ap": "10",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/044_i18n_front.png"
    },
    "Captain Amakna": {
        "name": "Captain Amakna",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/duel/1",
        "level": "6",
        "initiative": "8",
        "mp": "4",
        "hp": "12",
        "ap": "9",
        "edition": "Duel Pack",
        "img": "http://cdn.krosfinder.info/media/krs/EN/045_i18n_front.png"
    },
    "Merkator": {
        "name": "Merkator",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/duel/2",
        "level": "6",
        "initiative": "2",
        "mp": "3",
        "hp": "17",
        "ap": "8",
        "edition": "Duel Pack",
        "img": "http://cdn.krosfinder.info/media/krs/EN/046_i18n_front.png"
    },
    "Count Harebourg": {
        "name": "Count Harebourg",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/frig/1",
        "level": "6",
        "initiative": "8",
        "mp": "4",
        "hp": "16",
        "ap": "8",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/043_i18n_front.png"
    },
    "Lumino": {
        "name": "Lumino",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/multi/1",
        "level": "2",
        "initiative": "6",
        "mp": "4",
        "hp": "4",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/051_i18n_front.png"
    },
    "Krobax": {
        "name": "Krobax",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/multi/2",
        "level": "2",
        "initiative": "4",
        "mp": "3",
        "hp": "5",
        "ap": "5",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/047_i18n_front.png"
    },
    "Skale": {
        "name": "Skale",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/multi/3",
        "level": "2",
        "initiative": "4",
        "mp": "3",
        "hp": "6",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/049_i18n_front.png"
    },
    "Trank": {
        "name": "Trank",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/multi/4",
        "level": "2",
        "initiative": "4",
        "mp": "2",
        "hp": "9",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/050_i18n_front.png"
    },
    "Bellzebug": {
        "name": "Bellzebug",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/multi/5",
        "level": "2",
        "initiative": "4",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/048_i18n_front.png"
    },
    "Shadow": {
        "name": "Shadow",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/multi/6",
        "level": "2",
        "initiative": "3",
        "mp": "3",
        "hp": "7",
        "ap": "7",
        "edition": "Season 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/052_i18n_front.png"
    },
    "Grampy": {
        "name": "Grampy",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/kerub/1",
        "level": "4",
        "initiative": "4",
        "mp": "2",
        "hp": "11",
        "ap": "6",
        "edition": "Dofus Kerubim Krosmaster",
        "img": "http://cdn.krosfinder.info/media/krs/EN/056_i18n_front.png"
    },
    "Joris": {
        "name": "Joris",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/kerub/2",
        "level": "2",
        "initiative": "8",
        "mp": "5",
        "hp": "2",
        "ap": "5",
        "edition": "Dofus Kerubim Krosmaster",
        "img": "http://cdn.krosfinder.info/media/krs/EN/057_i18n_front.png"
    },
    "Kerub Crepin": {
        "name": "Kerub Crepin",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/kerub/3",
        "level": "4",
        "initiative": "9",
        "mp": "4",
        "hp": "13",
        "ap": "7",
        "edition": "Dofus Kerubim Krosmaster",
        "img": "http://cdn.krosfinder.info/media/krs/EN/058_i18n_front.png"
    },
    "Lou": {
        "name": "Lou",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/kerub/4",
        "level": "2",
        "initiative": "2",
        "mp": "3",
        "hp": "6",
        "ap": "6",
        "edition": "Dofus Kerubim Krosmaster",
        "img": "http://cdn.krosfinder.info/media/krs/EN/059_i18n_front.png"
    },
    "Wakfu Terminatot": {
        "name": "Wakfu Terminatot",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/term/1",
        "level": "3",
        "initiative": "7",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Krosmaster Terminatot",
        "img": "http://cdn.krosfinder.info/media/krs/EN/053_i18n_front.png",
        "status": "ban"
    },
    "Stasis Terminatot": {
        "name": "Stasis Terminatot",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/term/2",
        "level": "3",
        "initiative": "7",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Krosmaster Terminatot",
        "img": "http://cdn.krosfinder.info/media/krs/EN/054_i18n_front.png",
        "status": "ban"
    },
    "Goldenrod Terminatot": {
        "name": "Goldenrod Terminatot",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/term/3",
        "level": "3",
        "initiative": "7",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Krosmaster Terminatot",
        "img": "http://cdn.krosfinder.info/media/krs/EN/055_i18n_front.png",
        "status": "ban"
    },
    "Elogio": {
        "name": "Elogio",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks2/1",
        "level": "4",
        "initiative": "1",
        "mp": "3",
        "hp": "10",
        "ap": "7",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/060_i18n_front.png"
    },
    "Ira Tayte": {
        "name": "Ira Tayte",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks2/2",
        "level": "2",
        "initiative": "0",
        "mp": "3",
        "hp": "5",
        "ap": "6",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/061_i18n_front.png"
    },
    "Harry Sah": {
        "name": "Harry Sah",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks2/3",
        "level": "5",
        "initiative": "5",
        "mp": "3",
        "hp": "12",
        "ap": "7",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/062_i18n_front.png"
    },
    "Raul Bak": {
        "name": "Raul Bak",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks2/4",
        "level": "3",
        "initiative": "8",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/063_i18n_front.png"
    },
    "Henual": {
        "name": "Henual",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks2/5",
        "level": "2",
        "initiative": "6",
        "mp": "3",
        "hp": "5",
        "ap": "7",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/064_i18n_front.png",
        "status": "boss"
    },
    "Mike Locke": {
        "name": "Mike Locke",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks2/6",
        "level": "1",
        "initiative": "2",
        "mp": "2",
        "hp": "4",
        "ap": "6",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/065_i18n_front.png"
    },
    "Katsu Mi": {
        "name": "Katsu Mi",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks2/7",
        "level": "3",
        "initiative": "2",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/066_i18n_front.png"
    },
    "Kitty Rage": {
        "name": "Kitty Rage",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks2/8",
        "level": "5",
        "initiative": "5",
        "mp": "3",
        "hp": "16",
        "ap": "8",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/067_i18n_front.png"
    },
    "Emma Sacre": {
        "name": "Emma Sacre",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks2/9",
        "level": "4",
        "initiative": "0",
        "mp": "4",
        "hp": "12",
        "ap": "6",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/068_i18n_front.png"
    },
    "Chrissy Entrinch": {
        "name": "Chrissy Entrinch",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks2/10",
        "level": "3",
        "initiative": "3",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/069_i18n_front.png"
    },
    "Anne Gupp": {
        "name": "Anne Gupp",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks2/11",
        "level": "4",
        "initiative": "4",
        "mp": "3",
        "hp": "13",
        "ap": "7",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/070_i18n_front.png"
    },
    "Steamy Wonder": {
        "name": "Steamy Wonder",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks2/12",
        "level": "1",
        "initiative": "0",
        "mp": "3",
        "hp": "6",
        "ap": "5",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/071_i18n_front.png",
        "status": "boss"
    },
    "Diver Birel": {
        "name": "Diver Birel",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks2/13",
        "level": "3",
        "initiative": "6",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/072_i18n_front.png"
    },
    "Moe Lawr": {
        "name": "Moe Lawr",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks2/14",
        "level": "1",
        "initiative": "3",
        "mp": "3",
        "hp": "5",
        "ap": "5",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/073_i18n_front.png"
    },
    "Ghett Outadier": {
        "name": "Ghett Outadier",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks2/15",
        "level": "4",
        "initiative": "8",
        "mp": "4",
        "hp": "11",
        "ap": "7",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/074_i18n_front.png",
        "status": "boss"
    },
    "Pandalida": {
        "name": "Pandalida",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks2/16",
        "level": "3",
        "initiative": "5",
        "mp": "3",
        "hp": "11",
        "ap": "6",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/075_i18n_front.png"
    },
    "Malee Buhrum": {
        "name": "Malee Buhrum",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks2/17",
        "level": "5",
        "initiative": "5",
        "mp": "4",
        "hp": "13",
        "ap": "7",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/076_i18n_front.png"
    },
    "Poochan": {
        "name": "Poochan",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks2/18",
        "level": "1",
        "initiative": "5",
        "mp": "3",
        "hp": "5",
        "ap": "5",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/077_i18n_front.png",
        "status": "ban"
    },
    "Igar Dlador": {
        "name": "Igar Dlador",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks2/19",
        "level": "2",
        "initiative": "4",
        "mp": "3",
        "hp": "7",
        "ap": "6",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/081_i18n_front.png"
    },
    "Wally Sumwerels": {
        "name": "Wally Sumwerels",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks2/20",
        "level": "1",
        "initiative": "4",
        "mp": "3",
        "hp": "6",
        "ap": "5",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/082_i18n_front.png"
    },
    "Doo Rex": {
        "name": "Doo Rex",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks2/21",
        "level": "5",
        "initiative": "7",
        "mp": "4",
        "hp": "12",
        "ap": "7",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/083_i18n_front.png"
    },
    "Ayan": {
        "name": "Ayan",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks2/22",
        "level": "2",
        "initiative": "5",
        "mp": "3",
        "hp": "6",
        "ap": "6",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/078_i18n_front.png"
    },
    "Kivin": {
        "name": "Kivin",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks2/23",
        "level": "1",
        "initiative": "0",
        "mp": "3",
        "hp": "5",
        "ap": "5",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/079_i18n_front.png",
        "status": "boss"
    },
    "Theo": {
        "name": "Theo",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks2/24",
        "level": "4",
        "initiative": "10",
        "mp": "3",
        "hp": "10",
        "ap": "7",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/080_i18n_front.png",
        "status": "ban"
    },
    "Gein": {
        "name": "Gein",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks2/25",
        "level": "6",
        "initiative": "12",
        "mp": "5",
        "hp": "13",
        "ap": "7",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/091_i18n_front.png",
        "status": "boss"
    },
    "Adamai": {
        "name": "Adamai",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks2/26",
        "level": "3",
        "initiative": "7",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/089_i18n_front.png"
    },
    "Qilby": {
        "name": "Qilby",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks2/27",
        "level": "6",
        "initiative": "6",
        "mp": "2",
        "hp": "16",
        "ap": "10",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/090_i18n_front.png",
        "status": "boss"
    },
    "Amakna Riktus": {
        "name": "Amakna Riktus",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/dks2/28",
        "level": "2",
        "initiative": "3",
        "mp": "3",
        "hp": "7",
        "ap": "6",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/084_i18n_front.png"
    },
    "Bonta Riktus": {
        "name": "Bonta Riktus",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/dks2/29",
        "level": "2",
        "initiative": "3",
        "mp": "3",
        "hp": "5",
        "ap": "6",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/085_i18n_front.png"
    },
    "Sufokia Riktus": {
        "name": "Sufokia Riktus",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/dks2/30",
        "level": "2",
        "initiative": "3",
        "mp": "3",
        "hp": "6",
        "ap": "6",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/086_i18n_front.png"
    },
    "Brakmar Riktus": {
        "name": "Brakmar Riktus",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/dks2/31",
        "level": "2",
        "initiative": "3",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/087_i18n_front.png"
    },
    "Elite Riktus": {
        "name": "Elite Riktus",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks2/32",
        "level": "4",
        "initiative": "6",
        "mp": "3",
        "hp": "12",
        "ap": "8",
        "edition": "Dofus Krosmaster 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/088_i18n_front.png"
    },
    "Qilby Traitor": {
        "name": "Qilby Traitor",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf2/1",
        "level": "6",
        "initiative": "6",
        "mp": "3",
        "hp": "14",
        "ap": "10",
        "edition": "Exclusive Figurines 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/102_i18n_front.png"
    },
    "Yugo Young King": {
        "name": "Yugo Young King",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf2/2",
        "level": "4",
        "initiative": "8",
        "mp": "3",
        "hp": "12",
        "ap": "8",
        "edition": "Exclusive Figurines 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/092_i18n_front.png"
    },
    "Adamai Dragon": {
        "name": "Adamai Dragon",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf2/3",
        "level": "3",
        "initiative": "7",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Exclusive Figurines 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/093_i18n_front.png"
    },
    "Phaeris Devastated": {
        "name": "Phaeris Devastated",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf2/4",
        "level": "1",
        "initiative": "5",
        "mp": "3",
        "hp": "7",
        "ap": "5",
        "edition": "Exclusive Figurines 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/094_i18n_front.png"
    },
    "Cleophee": {
        "name": "Cleophee",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf2/5",
        "level": "2",
        "initiative": "7",
        "mp": "3",
        "hp": "7",
        "ap": "6",
        "edition": "Exclusive Figurines 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/095_i18n_front.png"
    },
    "Percedal Percylax": {
        "name": "Percedal Percylax",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf2/6",
        "level": "5",
        "initiative": "10",
        "mp": "3",
        "hp": "15",
        "ap": "7",
        "edition": "Exclusive Figurines 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/096_i18n_front.png"
    },
    "Arthur Bine": {
        "name": "Arthur Bine",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf2/7",
        "level": "3",
        "initiative": "3",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Exclusive Figurines 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/132_i18n_front.png",
        "status": "ban"
    },
    "Tiktokovitch": {
        "name": "Tiktokovitch",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/junior/1",
        "level": "3",
        "initiative": "4",
        "mp": "3",
        "hp": "6",
        "ap": "7",
        "edition": "Krosmaster Junior",
        "img": "http://cdn.krosfinder.info/media/krs/EN/098_i18n_front.png"
    },
    "Choppy Sue": {
        "name": "Choppy Sue",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/junior/2",
        "level": "3",
        "initiative": "1",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Krosmaster Junior",
        "img": "http://cdn.krosfinder.info/media/krs/EN/099_i18n_front.png"
    },
    "Mil Kluva": {
        "name": "Mil Kluva",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/junior/3",
        "level": "3",
        "initiative": "3",
        "mp": "3",
        "hp": "12",
        "ap": "6",
        "edition": "Krosmaster Junior",
        "img": "http://cdn.krosfinder.info/media/krs/EN/100_i18n_front.png"
    },
    "Kip Agau": {
        "name": "Kip Agau",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/junior/4",
        "level": "3",
        "initiative": "2",
        "mp": "4",
        "hp": "8",
        "ap": "6",
        "edition": "Krosmaster Junior",
        "img": "http://cdn.krosfinder.info/media/krs/EN/101_i18n_front.png"
    },
    "Queen of Thieves": {
        "name": "Queen of Thieves",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/duel2/1",
        "level": "4",
        "initiative": "8",
        "mp": "3",
        "hp": "14",
        "ap": "7",
        "edition": "Duel Pack 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/105_i18n_front.png"
    },
    "King Nidas": {
        "name": "King Nidas",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/duel2/2",
        "level": "4",
        "initiative": "7",
        "mp": "4",
        "hp": "12",
        "ap": "6",
        "edition": "Duel Pack 2",
        "img": "http://cdn.krosfinder.info/media/krs/EN/104_i18n_front.png"
    },
    "Djaul": {
        "name": "Djaul",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dark/1",
        "level": "1",
        "initiative": "4",
        "mp": "3",
        "hp": "6",
        "ap": "5",
        "edition": "Dark Heroes",
        "img": "http://cdn.krosfinder.info/media/krs/EN/106_i18n_front.png",
        "status": "boss"
    },
    "Dark Vlad": {
        "name": "Dark Vlad",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dark/2",
        "level": "2",
        "initiative": "7",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Dark Heroes",
        "img": "http://cdn.krosfinder.info/media/krs/EN/107_i18n_front.png"
    },
    "Kriss Krass": {
        "name": "Kriss Krass",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dark/3",
        "level": "3",
        "initiative": "7",
        "mp": "4",
        "hp": "10",
        "ap": "6",
        "edition": "Dark Heroes",
        "img": "http://cdn.krosfinder.info/media/krs/EN/108_i18n_front.png"
    },
    "Black Crow": {
        "name": "Black Crow",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dark/4",
        "level": "4",
        "initiative": "4",
        "mp": "4",
        "hp": "10",
        "ap": "7",
        "edition": "Dark Heroes",
        "img": "http://cdn.krosfinder.info/media/krs/EN/109_i18n_front.png",
        "status": "boss"
    },
    "Vampyro": {
        "name": "Vampyro",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dark/5",
        "level": "5",
        "initiative": "8",
        "mp": "4",
        "hp": "10",
        "ap": "7",
        "edition": "Dark Heroes",
        "img": "http://cdn.krosfinder.info/media/krs/EN/110_i18n_front.png"
    },
    "Katar": {
        "name": "Katar",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dark/6",
        "level": "6",
        "initiative": "9",
        "mp": "3",
        "hp": "12",
        "ap": "8",
        "edition": "Dark Heroes",
        "img": "http://cdn.krosfinder.info/media/krs/EN/111_i18n_front.png",
        "status": "boss"
    },
    "Kanniball Archer": {
        "name": "Kanniball Archer",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks3/1",
        "level": "1",
        "initiative": "1",
        "mp": "2",
        "hp": "4",
        "ap": "5",
        "edition": "Dofus Krosmaster 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/154_i18n_front.png"
    },
    "Kanniball Sarbak": {
        "name": "Kanniball Sarbak",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks3/2",
        "level": "1",
        "initiative": "5",
        "mp": "3",
        "hp": "6",
        "ap": "5",
        "edition": "Dofus Krosmaster 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/153_i18n_front.png"
    },
    "Kanniball Jav": {
        "name": "Kanniball Jav",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks3/3",
        "level": "2",
        "initiative": "6",
        "mp": "3",
        "hp": "6",
        "ap": "6",
        "edition": "Dofus Krosmaster 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/155_i18n_front.png"
    },
    "Kanniball Thierry": {
        "name": "Kanniball Thierry",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks3/4",
        "level": "2",
        "initiative": "2",
        "mp": "3",
        "hp": "6",
        "ap": "6",
        "edition": "Dofus Krosmaster 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/156_i18n_front.png"
    },
    "Kanniball Andchain": {
        "name": "Kanniball Andchain",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks3/5",
        "level": "3",
        "initiative": "7",
        "mp": "3",
        "hp": "11",
        "ap": "6",
        "edition": "Dofus Krosmaster 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/157_i18n_front.png"
    },
    "Moon": {
        "name": "Moon",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks3/6",
        "level": "5",
        "initiative": "1",
        "mp": "4",
        "hp": "12",
        "ap": "7",
        "edition": "Dofus Krosmaster 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/158_i18n_front.png"
    },
    "Dreggoog the Downunder": {
        "name": "Dreggoog the Downunder",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks3/7",
        "level": "2",
        "initiative": "5",
        "mp": "3",
        "hp": "6",
        "ap": "6",
        "edition": "Dofus Krosmaster 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/161_i18n_front.png"
    },
    "Dragossiper the Nag": {
        "name": "Dragossiper the Nag",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks3/8",
        "level": "3",
        "initiative": "5",
        "mp": "3",
        "hp": "10",
        "ap": "7",
        "edition": "Dofus Krosmaster 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/162_i18n_front.png"
    },
    "Dragostess": {
        "name": "Dragostess",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks3/9",
        "level": "4",
        "initiative": "5",
        "mp": "4",
        "hp": "11",
        "ap": "6",
        "edition": "Dofus Krosmaster 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/163_i18n_front.png"
    },
    "Crocabulia": {
        "name": "Crocabulia",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks3/10",
        "level": "5",
        "initiative": "8",
        "mp": "4",
        "hp": "15",
        "ap": "7",
        "edition": "Dofus Krosmaster 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/164_i18n_front.png"
    },
    "Hazwonarm": {
        "name": "Hazwonarm",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks3/11",
        "level": "2",
        "initiative": "2",
        "mp": "3",
        "hp": "6",
        "ap": "6",
        "edition": "Dofus Krosmaster 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/150_i18n_front.png"
    },
    "Boomba": {
        "name": "Boomba",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks3/12",
        "level": "1",
        "initiative": "3",
        "mp": "3",
        "hp": "4",
        "ap": "5",
        "edition": "Dofus Krosmaster 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/151_i18n_front.png"
    },
    "Buck Anear": {
        "name": "Buck Anear",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks3/13",
        "level": "4",
        "initiative": "9",
        "mp": "3",
        "hp": "10",
        "ap": "7",
        "edition": "Dofus Krosmaster 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/152_i18n_front.png"
    },
    "Deminoball": {
        "name": "Deminoball",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/dks3/14",
        "level": "3",
        "initiative": "7",
        "mp": "1",
        "hp": "13",
        "ap": "6",
        "edition": "Dofus Krosmaster 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/160_i18n_front.png"
    },
    "Minotoror": {
        "name": "Minotoror",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks3/15",
        "level": "4",
        "initiative": "7",
        "mp": "2",
        "hp": "14",
        "ap": "6",
        "edition": "Dofus Krosmaster 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/159_i18n_front.png"
    },
    "Otomai": {
        "name": "Otomai",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/dks3/16",
        "level": "6",
        "initiative": "0",
        "mp": "4",
        "hp": "12",
        "ap": "4",
        "edition": "Dofus Krosmaster 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/165_i18n_front.png"
    },
    "Dark Vlad Karnated": {
        "name": "Dark Vlad Karnated",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf3/1",
        "level": "3",
        "initiative": "7",
        "mp": "3",
        "hp": "12",
        "ap": "6",
        "edition": "Exclusive Figurines 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/114_i18n_front.png"
    },
    "Yugo Unleashed": {
        "name": "Yugo Unleashed",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf3/2",
        "level": "5",
        "initiative": "8",
        "mp": "1",
        "hp": "14",
        "ap": "8",
        "edition": "Exclusive Figurines 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/133_i18n_front.png"
    },
    "Ogrest Child": {
        "name": "Ogrest Child",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf3/3",
        "level": "1",
        "initiative": "5",
        "mp": "3",
        "hp": "4",
        "ap": "5",
        "edition": "Exclusive Figurines 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/112_i18n_front.png"
    },
    "Arty": {
        "name": "Arty",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf3/4",
        "level": "3",
        "initiative": "6",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Exclusive Figurines 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/113_i18n_front.png"
    },
    "Joris Master": {
        "name": "Joris Master",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf3/5",
        "level": "3",
        "initiative": "9",
        "mp": "3",
        "hp": "10",
        "ap": "9",
        "edition": "Exclusive Figurines 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/120_i18n_front.png"
    },
    "Grougaloragran Old": {
        "name": "Grougaloragran Old",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf3/6",
        "level": "1",
        "initiative": "2",
        "mp": "3",
        "hp": "6",
        "ap": "-",
        "edition": "Exclusive Figurines 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/121_i18n_front.png"
    },
    "Grampy Shopkeeper": {
        "name": "Grampy Shopkeeper",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf3/7",
        "level": "3",
        "initiative": "4",
        "mp": "3",
        "hp": "10",
        "ap": "4",
        "edition": "Exclusive Figurines 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/122_i18n_front.png"
    },
    "Darkli Moon": {
        "name": "Darkli Moon",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf3/8",
        "level": "2",
        "initiative": "6",
        "mp": "3",
        "hp": "6",
        "ap": "6",
        "edition": "Exclusive Figurines 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/123_i18n_front.png"
    },
    "Cardboard Tube Samurai": {
        "name": "Cardboard Tube Samurai",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf3/9",
        "level": "3",
        "initiative": "8",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Exclusive Figurines 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/172_i18n_front.png",
        "status": "ban"
    },
    "Nemesis Samurai": {
        "name": "Nemesis Samurai",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf3/10",
        "level": "3",
        "initiative": "5",
        "mp": "3",
        "hp": "9",
        "ap": "6",
        "edition": "Exclusive Figurines 3",
        "img": "http://cdn.krosfinder.info/media/krs/EN/173_i18n_front.png",
        "status": "ban"
    },
    "Royal Tofu": {
        "name": "Royal Tofu",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/qst/1",
        "level": "3",
        "initiative": "7",
        "mp": "4",
        "hp": "8",
        "ap": "6",
        "edition": "Krosmaster Quest",
        "img": "http://cdn.krosfinder.info/media/krs/EN/097_i18n_front.png"
    },
    "Royal Gobball": {
        "name": "Royal Gobball",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/qst/2",
        "level": "3",
        "initiative": "1",
        "mp": "3",
        "hp": "10",
        "ap": "7",
        "edition": "Krosmaster Quest",
        "img": "http://cdn.krosfinder.info/media/krs/EN/103_i18n_front.png"
    },
    "Le Chouque": {
        "name": "Le Chouque",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/piwate/1",
        "level": "5",
        "initiative": "4",
        "mp": "4",
        "hp": "12",
        "ap": "8",
        "edition": "Piwate Island",
        "img": "http://cdn.krosfinder.info/media/krs/EN/115_i18n_front.png"
    },
    "Percimol Controlled": {
        "name": "Percimol Controlled",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/oav/1",
        "level": "3",
        "initiative": "2",
        "mp": "3",
        "hp": "11",
        "ap": "6",
        "edition": "",
        "img": "http://cdn.krosfinder.info/media/krs/EN/166_i18n_front.png"
    },
    "Ush": {
        "name": "Ush",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/oav/2",
        "level": "4",
        "initiative": "6",
        "mp": "3",
        "hp": "12",
        "ap": "7",
        "edition": "",
        "img": "http://cdn.krosfinder.info/media/krs/EN/167_i18n_front.png"
    },
    "Remington Smisse Mercenary": {
        "name": "Remington Smisse Mercenary",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/oav/3",
        "level": "4",
        "initiative": "7",
        "mp": "3",
        "hp": "12",
        "ap": "7",
        "edition": "",
        "img": "http://cdn.krosfinder.info/media/krs/EN/168_i18n_front.png"
    },
    "Yugo Exalted": {
        "name": "Yugo Exalted",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/oav/4",
        "level": "4",
        "initiative": "7",
        "mp": "4",
        "hp": "12",
        "ap": "7",
        "edition": "",
        "img": "http://cdn.krosfinder.info/media/krs/EN/169_i18n_front.png"
    },
    "Maskemane Psychopath": {
        "name": "Maskemane Psychopath",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/oav/5",
        "level": "1",
        "initiative": "1",
        "mp": "3",
        "hp": "7",
        "ap": "5",
        "edition": "",
        "img": "http://cdn.krosfinder.info/media/krs/EN/170_i18n_front.png"
    },
    "Atcham": {
        "name": "Atcham",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/oav/6",
        "level": "2",
        "initiative": "4",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "",
        "img": "http://cdn.krosfinder.info/media/krs/EN/171_i18n_front.png"
    },
    "Maskemane Classic": {
        "name": "Maskemane Classic",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf4/1",
        "level": "1",
        "initiative": "1",
        "mp": "3",
        "hp": "5",
        "ap": "6",
        "edition": "Exclusive Figurines 4",
        "img": "http://cdn.krosfinder.info/media/krs/EN/174_i18n_front.png"
    },
    "Maskemane Coward": {
        "name": "Maskemane Coward",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/exf4/2",
        "level": "1",
        "initiative": "1",
        "mp": "4",
        "hp": "4",
        "ap": "5",
        "edition": "Exclusive Figurines 4",
        "img": "http://cdn.krosfinder.info/media/krs/EN/175_i18n_front.png"
    },
    "Argon Gass Eternal 1": {
        "name": "Argon Gass Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/1",
        "level": "3",
        "initiative": "3",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/201_i18n_front.png"
    },
    "Amalia Eternal 1": {
        "name": "Amalia Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/2",
        "level": "3",
        "initiative": "3",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/202_i18n_front.png"
    },
    "Evangelyne Eternal 1": {
        "name": "Evangelyne Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/3",
        "level": "3",
        "initiative": "8",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/203_i18n_front.png"
    },
    "Nox Eternal 1": {
        "name": "Nox Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/4",
        "level": "6",
        "initiative": "10",
        "mp": "2",
        "hp": "13",
        "ap": "8",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/204_i18n_front.png"
    },
    "Ruel Stroud Eternal 1": {
        "name": "Ruel Stroud Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/5",
        "level": "3",
        "initiative": "6",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/205_i18n_front.png"
    },
    "Percedal Eternal 1": {
        "name": "Percedal Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/6",
        "level": "3",
        "initiative": "3",
        "mp": "3",
        "hp": "11",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/206_i18n_front.png"
    },
    "Yugo Eternal 1": {
        "name": "Yugo Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/7",
        "level": "3",
        "initiative": "7",
        "mp": "3",
        "hp": "8",
        "ap": "7",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/207_i18n_front.png"
    },
    "Bill Tell Eternal 1": {
        "name": "Bill Tell Eternal 1",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/et1/8",
        "level": "3",
        "initiative": "7",
        "mp": "3",
        "hp": "6",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/208_i18n_front.png"
    },
    "Lil Healey Eternal 1": {
        "name": "Lil Healey Eternal 1",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/et1/9",
        "level": "3",
        "initiative": "5",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/209_i18n_front.png"
    },
    "Bad Aboum Eternal 1": {
        "name": "Bad Aboum Eternal 1",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/et1/10",
        "level": "3",
        "initiative": "4",
        "mp": "4",
        "hp": "10",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/210_i18n_front.png"
    },
    "Anna Tommy Eternal 1": {
        "name": "Anna Tommy Eternal 1",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/et1/11",
        "level": "3",
        "initiative": "9",
        "mp": "3",
        "hp": "12",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/211_i18n_front.png"
    },
    "Oscar Kass Eternal 1": {
        "name": "Oscar Kass Eternal 1",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/et1/12",
        "level": "3",
        "initiative": "4",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/212_i18n_front.png"
    },
    "Kassius Kaos Eternal 1": {
        "name": "Kassius Kaos Eternal 1",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/et1/13",
        "level": "3",
        "initiative": "4",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/213_i18n_front.png"
    },
    "Queen of the Tofus Eternal 1": {
        "name": "Queen of the Tofus Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/14",
        "level": "3",
        "initiative": "8",
        "mp": "4",
        "hp": "8",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/214_i18n_front.png"
    },
    "King of the Gobballs Eternal 1": {
        "name": "King of the Gobballs Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/15",
        "level": "3",
        "initiative": "2",
        "mp": "3",
        "hp": "11",
        "ap": "7",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/215_i18n_front.png"
    },
    "Jems Blond Eternal 1": {
        "name": "Jems Blond Eternal 1",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/et1/16",
        "level": "4",
        "initiative": "8",
        "mp": "4",
        "hp": "8",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/216_i18n_front.png"
    },
    "Luk Ylook Eternal 1": {
        "name": "Luk Ylook Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/17",
        "level": "2",
        "initiative": "6",
        "mp": "3",
        "hp": "5",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/217_i18n_front.png"
    },
    "Dani OShun Eternal 1": {
        "name": "Dani OShun Eternal 1",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/et1/18",
        "level": "4",
        "initiative": "5",
        "mp": "4",
        "hp": "13",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/218_i18n_front.png"
    },
    "Naz Rael Eternal 1": {
        "name": "Naz Rael Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/19",
        "level": "2",
        "initiative": "3",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/219_i18n_front.png"
    },
    "Quentin Flush Eternal 1": {
        "name": "Quentin Flush Eternal 1",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/et1/20",
        "level": "1",
        "initiative": "2",
        "mp": "3",
        "hp": "6",
        "ap": "5",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/220_i18n_front.png"
    },
    "Ally McZeal Eternal 1": {
        "name": "Ally McZeal Eternal 1",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/et1/21",
        "level": "4",
        "initiative": "3",
        "mp": "3",
        "hp": "11",
        "ap": "7",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/221_i18n_front.png"
    },
    "Di Curey Eternal 1": {
        "name": "Di Curey Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/22",
        "level": "1",
        "initiative": "3",
        "mp": "3",
        "hp": "5",
        "ap": "5",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/222_i18n_front.png"
    },
    "Goultard Eternal 1": {
        "name": "Goultard Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/23",
        "level": "6",
        "initiative": "7",
        "mp": "4",
        "hp": "15",
        "ap": "8",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/223_i18n_front.png"
    },
    "Remington Smisse Eternal 1": {
        "name": "Remington Smisse Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/24",
        "level": "5",
        "initiative": "5",
        "mp": "4",
        "hp": "13",
        "ap": "7",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/224_i18n_front.png"
    },
    "Boo Ming Eternal 1": {
        "name": "Boo Ming Eternal 1",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/et1/25",
        "level": "2",
        "initiative": "3",
        "mp": "3",
        "hp": "7",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/225_i18n_front.png"
    },
    "Coa Gulary Eternal 1": {
        "name": "Coa Gulary Eternal 1",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/et1/26",
        "level": "1",
        "initiative": "6",
        "mp": "3",
        "hp": "7",
        "ap": "5",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/226_i18n_front.png"
    },
    "Clot the Crapulous Eternal 1": {
        "name": "Clot the Crapulous Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/27",
        "level": "4",
        "initiative": "4",
        "mp": "3",
        "hp": "14",
        "ap": "7",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/227_i18n_front.png"
    },
    "Klor Ofil Eternal 1": {
        "name": "Klor Ofil Eternal 1",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/et1/28",
        "level": "2",
        "initiative": "4",
        "mp": "3",
        "hp": "6",
        "ap": "5",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/228_i18n_front.png"
    },
    "Fern Sockem Eternal 1": {
        "name": "Fern Sockem Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/29",
        "level": "1",
        "initiative": "2",
        "mp": "3",
        "hp": "6",
        "ap": "5",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/229_i18n_front.png"
    },
    "Makum Bah Eternal 1": {
        "name": "Makum Bah Eternal 1",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/et1/30",
        "level": "4",
        "initiative": "6",
        "mp": "3",
        "hp": "13",
        "ap": "7",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/230_i18n_front.png"
    },
    "Srammy Eternal 1": {
        "name": "Srammy Eternal 1",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/et1/31",
        "level": "2",
        "initiative": "9",
        "mp": "3",
        "hp": "6",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/231_i18n_front.png"
    },
    "Fraktor Eternal 1": {
        "name": "Fraktor Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/32",
        "level": "4",
        "initiative": "4",
        "mp": "3",
        "hp": "13",
        "ap": "7",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/232_i18n_front.png"
    },
    "Maskun John Eternal 1": {
        "name": "Maskun John Eternal 1",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/et1/33",
        "level": "2",
        "initiative": "4",
        "mp": "3",
        "hp": "7",
        "ap": "7",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/233_i18n_front.png"
    },
    "Victor don Voom Eternal 1": {
        "name": "Victor don Voom Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/34",
        "level": "5",
        "initiative": "9",
        "mp": "4",
        "hp": "14",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/234_i18n_front.png"
    },
    "Percimol Eternal 1": {
        "name": "Percimol Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/35",
        "level": "5",
        "initiative": "2",
        "mp": "3",
        "hp": "17",
        "ap": "7",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/235_i18n_front.png"
    },
    "Shak Shaka Eternal 1": {
        "name": "Shak Shaka Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/36",
        "level": "5",
        "initiative": "0",
        "mp": "3",
        "hp": "15",
        "ap": "7",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/236_i18n_front.png"
    },
    "Darkness Knight Eternal 1": {
        "name": "Darkness Knight Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/37",
        "level": "6",
        "initiative": "8",
        "mp": "4",
        "hp": "15",
        "ap": "7",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/237_i18n_front.png"
    },
    "Cloud Knight Eternal 1": {
        "name": "Cloud Knight Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/38",
        "level": "3",
        "initiative": "6",
        "mp": "4",
        "hp": "9",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/238_i18n_front.png"
    },
    "Drop Knight Eternal 1": {
        "name": "Drop Knight Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/39",
        "level": "3",
        "initiative": "2",
        "mp": "3",
        "hp": "10",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/239_i18n_front.png"
    },
    "Flame Knight Eternal 1": {
        "name": "Flame Knight Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/40",
        "level": "3",
        "initiative": "4",
        "mp": "3",
        "hp": "9",
        "ap": "7",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/240_i18n_front.png"
    },
    "Leaf Knight Eternal 1": {
        "name": "Leaf Knight Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/41",
        "level": "3",
        "initiative": "2",
        "mp": "3",
        "hp": "11",
        "ap": "7",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/241_i18n_front.png"
    },
    "Goultard the Barbarian Eternal 1": {
        "name": "Goultard the Barbarian Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/42",
        "level": "6",
        "initiative": "5",
        "mp": "3",
        "hp": "25",
        "ap": "8",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/242_i18n_front.png"
    },
    "Count Harebourg Eternal 1": {
        "name": "Count Harebourg Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/43",
        "level": "6",
        "initiative": "8",
        "mp": "4",
        "hp": "15",
        "ap": "8",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/243_i18n_front.png"
    },
    "Count Frigost Eternal 1": {
        "name": "Count Frigost Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/44",
        "level": "6",
        "initiative": "6",
        "mp": "5",
        "hp": "15",
        "ap": "10",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/244_i18n_front.png"
    },
    "Captain Amakna Eternal 1": {
        "name": "Captain Amakna Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/45",
        "level": "6",
        "initiative": "8",
        "mp": "4",
        "hp": "13",
        "ap": "9",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/245_i18n_front.png"
    },
    "Merkator Eternal 1": {
        "name": "Merkator Eternal 1",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/et1/46",
        "level": "6",
        "initiative": "7",
        "mp": "3",
        "hp": "14",
        "ap": "8",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/246_i18n_front.png"
    },
    "Krobax Eternal 1": {
        "name": "Krobax Eternal 1",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/et1/47",
        "level": "2",
        "initiative": "4",
        "mp": "3",
        "hp": "5",
        "ap": "5",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/247_i18n_front.png"
    },
    "Belezebug Eternal 1": {
        "name": "Belezebug Eternal 1",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/et1/48",
        "level": "2",
        "initiative": "4",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/248_i18n_front.png"
    },
    "Skale Eternal 1": {
        "name": "Skale Eternal 1",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/et1/49",
        "level": "2",
        "initiative": "4",
        "mp": "3",
        "hp": "6",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/249_i18n_front.png"
    },
    "Trank Eternal 1": {
        "name": "Trank Eternal 1",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/et1/50",
        "level": "2",
        "initiative": "4",
        "mp": "2",
        "hp": "9",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/250_i18n_front.png"
    },
    "Lumino Eternal 1": {
        "name": "Lumino Eternal 1",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/et1/51",
        "level": "2",
        "initiative": "6",
        "mp": "4",
        "hp": "3",
        "ap": "6",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/251_i18n_front.png"
    },
    "Shadow Eternal 1": {
        "name": "Shadow Eternal 1",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/et1/52",
        "level": "2",
        "initiative": "2",
        "mp": "3",
        "hp": "7",
        "ap": "7",
        "edition": "Eternal 1",
        "img": "http://cdn.krosfinder.info/media/krs/EN/252_i18n_front.png"
    },
    "Bakara": {
        "name": "bakara",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/ks4/8",
        "level": "4",
        "initiative": "7",
        "mp": "3",
        "hp": "11",
        "ap": "7",
        "edition": "Krosmaster Arena 2.0",
        "img": "http://cdn.krosfinder.info/media/krs/RU/125_i18n_front.png",
        "status": "boss"
    },
    "Skidmonk": {
        "name": "Skidmonk",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/cpk/14",
        "level": "3",
        "initiative": "5",
        "mp": "2",
        "hp": "9",
        "ap": "6",
        "edition": "Cemetery Park",
        "img": "http://cdn.krosfinder.info/media/krs/RU/147_i18n_front.png"
    },
    "Friar Tubs": {
        "name": "Friar Tubs",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/cpk/15",
        "level": "4",
        "initiative": "5",
        "mp": "3",
        "hp": "12",
        "ap": "7",
        "edition": "Cemetery Park",
        "img": "http://cdn.krosfinder.info/media/krs/RU/148_i18n_front.png"
    },
    "Felonious Monk": {
        "name": "Felonious Monk",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/cpk/16",
        "level": "3",
        "initiative": "5",
        "mp": "3",
        "hp": "9",
        "ap": "7",
        "edition": "Cemetery Park",
        "img": "http://cdn.krosfinder.info/media/krs/RU/149_i18n_front.png"
    },
    "Master Vampire": {
        "name": "Master Vampire",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/cpk/6",
        "level": "3",
        "initiative": "7",
        "mp": "3",
        "hp": "10",
        "ap": "7",
        "edition": "Cemetery Park",
        "img": "http://cdn.krosfinder.info/media/krs/RU/139_i18n_front.png"
    },
    "Lord Crow": {
        "name": "Lord Crow",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/cpk/1",
        "level": "3",
        "initiative": "7",
        "mp": "3",
        "hp": "9",
        "ap": "7",
        "edition": "Cemetery Park",
        "img": "http://cdn.krosfinder.info/media/krs/RU/134_i18n_front.png"
    },
    "Grampy Protector": {
        "name": "Grampy Protector",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/ks4/4",
        "level": "4",
        "initiative": "6",
        "mp": "3",
        "hp": "12",
        "ap": "7",
        "edition": "Krosmaster Arena 2.0",
        "img": "http://cdn.krosfinder.info/media/krs/RU/128_i18n_front.png"
    },
    "Jahash": {
        "name": "Jahash",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/ks4/6",
        "level": "4",
        "initiative": "1",
        "mp": "3",
        "hp": "12",
        "ap": "7",
        "edition": "Krosmaster Arena 2.0",
        "img": "http://cdn.krosfinder.info/media/krs/RU/124_i18n_front.png"
    },
    "Julith": {
        "name": "Julith",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/ks4/1",
        "level": "4",
        "initiative": "11",
        "mp": "3",
        "hp": "13",
        "ap": "7",
        "edition": "Krosmaster Arena 2.0",
        "img": "http://cdn.krosfinder.info/media/krs/RU/127_i18n_front.png",
        "status": "boss"
    },
    "Puny Vampire": {
        "name": "Puny Vampire",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/cpk/7",
        "level": "1",
        "initiative": "4",
        "mp": "3",
        "hp": "6",
        "ap": "5",
        "edition": "Cemetery Park",
        "img": "http://cdn.krosfinder.info/media/krs/RU/140_i18n_front.png"
    },
    "Joris Swashbuckler": {
        "name": "Joris Swashbuckler",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/ks4/5",
        "level": "2",
        "initiative": "4",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Krosmaster Arena 2.0",
        "img": "http://cdn.krosfinder.info/media/krs/RU/126_i18n_front.png"
    },
    "Persee Phore": {
        "name": "Persee Phore",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/cpk/5",
        "level": "2",
        "initiative": "7",
        "mp": "3",
        "hp": "7",
        "ap": "5",
        "edition": "Cemetery Park",
        "img": "http://cdn.krosfinder.info/media/krs/RU/138_i18n_front.png"
    },
    "Mopy King": {
        "name": "Mopy King",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/cpk/3",
        "level": "4",
        "initiative": "8",
        "mp": "4",
        "hp": "13",
        "ap": "7",
        "edition": "Cemetery Park",
        "img": "http://cdn.krosfinder.info/media/krs/RU/136_i18n_front.png"
    },
    "Lilotte": {
        "name": "Lilotte",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/ks4/2",
        "level": "2",
        "initiative": "2",
        "mp": "3",
        "hp": "6",
        "ap": "6",
        "edition": "Krosmaster Arena 2.0",
        "img": "http://cdn.krosfinder.info/media/krs/RU/130_i18n_front.png"
    },
    "Marline": {
        "name": "Marline",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/ks4/3",
        "level": "2",
        "initiative": "4",
        "mp": "3",
        "hp": "6",
        "ap": "6",
        "edition": "Krosmaster Arena 2.0",
        "img": "http://cdn.krosfinder.info/media/krs/RU/131_i18n_front.png"
    },
    "The Nun": {
        "name": "The Nun",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/cpk/4",
        "level": "5",
        "initiative": "8",
        "mp": "2",
        "hp": "14",
        "ap": "8",
        "edition": "Cemetery Park",
        "img": "http://cdn.krosfinder.info/media/krs/RU/137_i18n_front.png"
    },
    "Grim Preacher": {
        "name": "Grim Preacher",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/cpk/13",
        "level": "2",
        "initiative": "5",
        "mp": "3",
        "hp": "5",
        "ap": "7",
        "edition": "Cemetery Park",
        "img": "http://cdn.krosfinder.info/media/krs/RU/146_i18n_front.png"
    },
    "Sphincter Cell": {
        "name": "Sphincter Cell",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/cpk/2",
        "level": "4",
        "initiative": "6",
        "mp": "3",
        "hp": "13",
        "ap": "7",
        "edition": "Cemetery Park",
        "img": "http://cdn.krosfinder.info/media/krs/RU/135_i18n_front.png"
    },
    "Khan Karkass": {
        "name": "Khan Karkass",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/ks4/7",
        "level": "2",
        "initiative": "6",
        "mp": "3",
        "hp": "8",
        "ap": "6",
        "edition": "Krosmaster Arena 2.0",
        "img": "http://cdn.krosfinder.info/media/krs/RU/129_i18n_front.png"
    },
    "Chafer Lancer": {
        "name": "Chafer Lancer",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/cpk/10",
        "level": "1",
        "initiative": "3",
        "mp": "3",
        "hp": "6",
        "ap": "5",
        "edition": "Cemetery Park",
        "img": "http://cdn.krosfinder.info/media/krs/RU/143_i18n_front.png"
    },
    "Chafer Archer": {
        "name": "Chafer Archer",
        "color": "black",
        "link": "http://krosfinder.com/ru/ed/cpk/8",
        "level": "2",
        "initiative": "3",
        "mp": "3",
        "hp": "5",
        "ap": "6",
        "edition": "Cemetery Park",
        "img": "http://cdn.krosfinder.info/media/krs/RU/141_i18n_front.png"
    },
    "Invisible Chafer": {
        "name": "Invisible Chafer",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/cpk/11",
        "level": "3",
        "initiative": "3",
        "mp": "3",
        "hp": "9",
        "ap": "6",
        "edition": "Cemetery Park",
        "img": "http://cdn.krosfinder.info/media/krs/RU/144_i18n_front.png"
    },
    "Chafer Foot Soldier": {
        "name": "Chafer Foot Soldier",
        "color": "white",
        "link": "http://krosfinder.com/ru/ed/cpk/9",
        "level": "1",
        "initiative": "3",
        "mp": "3",
        "hp": "6",
        "ap": "5",
        "edition": "Cemetery Park",
        "img": "http://cdn.krosfinder.info/media/krs/RU/142_i18n_front.png"
    },
    "Elite Chafer": {
        "name": "Elite Chafer",
        "color": "yellow",
        "link": "http://krosfinder.com/ru/ed/cpk/12",
        "level": "4",
        "initiative": "3",
        "mp": "3",
        "hp": "11",
        "ap": "6",
        "edition": "Cemetery Park",
        "img": "http://cdn.krosfinder.info/media/krs/RU/145_i18n_front.png"
    }
};

/*
var list = {};
$('[itemprop="itemListElement"]').each(function (e, val) {
    list[val.innerHTML] = {
        'link': val.href,
        'level': 1
    };
});
copy(list);

var list = {};
$('.table tr').each(function (e, val) {
    if (e > 0) {
        var color = $(val).find('td:nth-child(2)')[0].className;
        var name = $(val).find('td:nth-child(3)').find('a')[0].innerHTML;
        var link = $(val).find('td:nth-child(3)').find('a')[0].href;
        var level = $(val).find('td:nth-child(4)')[0].innerText;
        var initiative = $(val).find('td:nth-child(5)')[0].innerText;
        var mp = $(val).find('td:nth-child(6)')[0].innerText;
        var hp = $(val).find('td:nth-child(7)')[0].innerText;
        var ap = $(val).find('td:nth-child(8)')[0].innerText;
        var edition = $(val).find('td:nth-child(9)')[0].innerText;

        if (edition=='Eternal 1') {
            name += ' Eternal 1';
        }

        list[name] = {
            'name':name,
            'color': color,
            'link': link,
            'level': level,
            'initiative': initiative,
            'mp': mp,
            'hp': hp,
            'ap': ap,
            'edition': edition
        };
    }

});
copy(list);

var data_img = JSON.parse(localStorage.getItem("data_img"));
$('[itemprop="itemListElement"] img').each(function (e, val) {
    data_img.push(val.src);
});
localStorage.setItem("data", JSON.stringify(data_img));
*/


// var data_img = [
//     "http://cdn.krosfinder.info/media/krs/EN/014_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/015_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/025_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/010_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/024_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/033_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/013_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/034_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/008_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/016_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/017_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/009_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/021_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/022_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/031_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/012_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/032_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/026_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/011_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/027_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/028_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/030_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/029_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/020_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/018_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/019_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/035_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/036_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/023_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/038_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/039_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/040_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/041_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/037_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/001_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/002_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/003_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/004_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/005_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/006_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/007_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/042_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/044_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/045_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/046_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/043_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/051_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/047_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/049_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/050_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/048_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/052_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/056_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/057_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/058_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/059_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/053_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/054_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/055_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/060_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/061_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/062_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/063_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/064_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/065_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/066_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/067_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/068_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/069_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/070_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/071_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/072_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/073_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/074_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/075_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/076_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/077_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/081_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/082_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/083_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/078_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/079_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/080_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/091_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/089_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/090_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/084_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/085_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/086_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/087_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/088_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/102_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/092_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/093_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/094_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/095_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/096_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/132_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/098_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/099_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/100_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/101_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/105_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/104_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/106_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/107_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/108_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/109_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/110_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/111_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/154_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/153_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/155_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/156_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/157_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/158_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/161_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/162_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/163_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/164_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/150_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/151_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/152_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/160_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/159_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/165_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/114_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/133_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/112_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/113_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/120_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/121_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/122_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/123_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/172_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/172_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/173_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/173_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/097_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/103_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/115_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/118_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/119_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/166_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/167_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/168_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/169_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/170_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/171_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/174_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/175_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/201_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/202_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/203_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/204_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/205_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/206_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/207_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/208_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/209_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/210_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/211_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/212_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/213_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/214_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/215_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/216_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/217_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/218_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/219_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/220_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/221_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/222_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/223_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/224_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/225_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/226_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/227_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/228_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/229_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/230_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/231_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/232_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/233_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/234_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/235_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/236_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/237_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/238_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/239_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/240_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/241_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/242_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/243_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/244_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/245_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/246_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/247_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/248_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/249_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/250_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/251_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/EN/252_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/125_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/147_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/148_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/149_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/139_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/134_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/128_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/124_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/127_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/140_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/126_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/138_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/136_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/130_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/131_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/137_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/146_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/135_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/129_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/143_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/141_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/144_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/142_i18n_front.png",
//     "http://cdn.krosfinder.info/media/krs/RU/145_i18n_front.png"
// ];

// var busy = 0;
// var temp1 = '';
// var temp2 = '';
// var i = 0;
// for (var val in krosmasters) {
//     if (val == 'Royal Tofu') {
//         busy = 1;
//     }
//     if (busy) {
//         temp1=val;
//         if (i==0) {
//             temp1=val;
//             i++;
//         } else if(i==2) {
//             temp2=val;
//             i++;
//         } else if (i==3) {
//             krosmasters[temp1]['img']=krosmasters[val]['img'];
//             temp1 = temp2;
//             temp2 = val;
//         }
//     }
// };
// console.log(krosmasters);